### PR TITLE
More accurate yellow/gold-ish color.

### PR DESCRIPTION
**Pull request by ItsCEED**
More visible overall.

### CODE REVIEW

**Comment by gogodr** [comment]
I was going to comment that the color is being used in a couple more stylesheets and it would be better to refactor it and put it in a variable.

**Comment by ItsCEED** [comment]
I was about to edit #12 and say that.
My skills are not allowing that kind of move, even if they do, I bet you'll do it in less than 5 minutes, for me it will take some more!

I rather stick to suggestions and PR whenever I feel confident about a change!

**Comment by gogodr** [comment]
No problem I will take this PR and make the refactoring on top, thanks ✌

**Comment by gogodr** [comment]
Many things changed with the structure of the project on the last update. I am going to tackle this is a new branch. ✌

**Pull request closed without merging**
